defaults:
  - _self_

selector_model:
  threshold: 0.5
  sbert_name: "sentence-transformers/all-MiniLM-L6-v2"
  loss:
    l_comp: 0.1
    l_s: 0.01
    l_tv: 10.0
    tau: 0.07
  optim:
    lr: 5e-5
    weight_decay: 1e-2
    betas: [0.9, 0.999]

train:
  num_selectors: 10
  epochs_per_selector: 1
  grad_clip: 1.0

data:
  rebuild_ds: False
  train:
    dataset: "wikiann"
    config: "en"
    batch_size: 32
    num_workers: 0
    subset: 1.0
    shuffle: True
  eval:
    dataset: "wikiann"
    config: "en"
    split: "validation"
    batch_size: 32
    num_workers: 0
    subset: 1.0
    shuffle: False
  dev:
    dataset: null
    config: null
    split: "test"
    batch_size: 32
    num_workers: 0
    subset: 1.0
    shuffle: False

eval:
  eval_only: False

runtime:
  num_threads: 8

device: "cuda"

logging:
  metrics_only: False

dora:
  exclude: ["eval.*", "data.rebuild_ds", "logging.*"]
